#!/usr/bin/env node
import 'reflect-metadata'
import { Ignitor } from '@adonisjs/core'
import { fileURLToPath } from 'node:url'

const currentDir = fileURLToPath(new URL('.', import.meta.url))
const ignitor = new Ignitor(currentDir)

await ignitor.ace().handle(process.argv.slice(2))
